wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/code/rl.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1649083374
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      3:
      - 16
      - 22
      - 35
      4: 3.8.12
      5: 0.12.11
      8:
      - 5
eval_callback:
  desc: null
  value:
    best_model_save_path: ./logs_real/
    callback_on_new_best: null
    deterministic: false
    eval_freq: 4096
    log_path: ./logs_real/
    n_eval_episodes: 20
    render: false
    verbose: 1
    warn: true
file_handling:
  desc: null
  value:
    continue_training_model_filename: null
    continue_training_model_folder: trained_models
    load_model_filename: rgb_4_objects
    load_model_folder: trained_models
    save_model_filename: rgb_4_objects
    save_model_folder: trained_models
    tb_log_folder: ppo_lift_4_objects_tensorboard
    tb_log_name: rgb_4_objects_plot
gymwrapper:
  desc: null
  value:
    observations:
    - custom_image
    smaller_action_space: true
norm_obs_keys:
  desc: null
  value: []
normalize_obs:
  desc: null
  value: false
normalize_rew:
  desc: null
  value: false
robosuite:
  desc: null
  value:
    camera_heights: 300
    camera_names: custom
    camera_widths: 486
    control_freq: 20
    controller_configs:
      control_delta: true
      damping_ratio: 1
      damping_ratio_limits:
      - 0
      - 10
      impedance_mode: fixed
      input_max: 1
      input_min: -1
      interpolation: null
      kp: 150
      kp_limits:
      - 0
      - 300
      orientation_limits: null
      output_max:
      - 0.05
      - 0.05
      - 0.05
      - 0.5
      - 0.5
      - 0.5
      output_min:
      - -0.05
      - -0.05
      - -0.05
      - -0.5
      - -0.5
      - -0.5
      position_limits": null
      ramp_ratio: 0.2
      type: OSC_POSE
      uncouple_pos_ori: true
    custom_camera_attrib:
      fovy: 36
    custom_camera_conversion: true
    custom_camera_name: custom
    custom_camera_trans_matrix:
    - - 0.011358
      - 0.433358
      - -0.90115
      - 1220.739746
    - - 0.961834
      - 0.241668
      - 0.12834
      - -129.767868
    - - 0.273397
      - -0.868215
      - -0.414073
      - 503.424103
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
    gripper_types: Robotiq85Gripper_iiwa_14
    has_offscreen_renderer: true
    has_renderer: false
    horizon: 400
    reward_shaping: true
    robots: IIWA_14
    use_camera_obs: true
    use_object_obs: false
sb_config:
  desc: null
  value:
    check_pt_interval: 1000
    num_procs: 2
    policy: PPO
    total_timesteps: 200000
sb_policy:
  desc: null
  value:
    _init_setup_model: true
    batch_size: 64
    clip_range: 0.2
    clip_range_vf: null
    create_eval_env: false
    device: auto
    ent_coef: 0.0
    gae_lambda: 0.95
    gamma: 0.99
    learning_rate: 0.0003
    max_grad_norm: 0.5
    n_epochs: 10
    n_steps: 1
    policy_kwargs: null
    sde_sample_freq: -1
    seed: null
    target_kl: null
    use_sde: false
    verbose: 1
    vf_coef: 0.5
seed:
  desc: null
  value: 0
training:
  desc: null
  value: true
wandb:
  desc: null
  value:
    project: sb3_lift_real
    save_code: true
    sync_tensorboard: true
wandb_callback:
  desc: null
  value:
    gradient_save_freq: 10000
    verbose: 2
