seed: 3
training: True   # Whether to train a model or not

wandb_filename: "ludvik_tester_rgbd"

# Settings for stable-baselines RL algorithm
sb_config:
  total_timesteps: 14.0e+6 
  num_procs: 24
  policy: 'PPO'

learning_rate_schedular: True


# Settings for normalization
normalize_obs: True
normalize_rew: True
norm_obs_keys: ['robot0_eef_pos', 'gripper_status']    #List of obs keys to normalize

use_domain_rand: False

# Policy settings
sb_policy:
  type: "MultiInputPolicy"
  learning_rate: 0.0001 
  n_steps: 3072
  batch_size: 512 
  n_epochs: 10 
  gamma: 0.99 
  gae_lambda: 0.95 
  clip_range: 0.2 
  clip_range_vf: null 
  ent_coef: 0.0 
  vf_coef: 0.5 
  max_grad_norm: 0.5
  use_sde: False 
  sde_sample_freq: -1 
  target_kl: null 
  create_eval_env: False 
  verbose: 1 
  seed: null
  device: 'auto' 
  _init_setup_model: True
  policy_kwargs:
    features_extractor_class: true 
    net_arch:
      - 100 
      - pi: 
        - 300
        - 200    # Custom actor network
        vf: 
        - 300
        - 200    # Value function network

# Specify environment
robosuite:
  env_id: "Lift_edit"
  robots: "IIWA_14_modified"
  gripper_types: "Robotiq85Gripper_iiwa_14"      
  has_renderer: False                    
  has_offscreen_renderer: True           
  control_freq: 10                       
  horizon: 200
  camera_heights: 84
  camera_widths: 84                          
  use_object_obs: False                  
  use_camera_obs: True
  reward_shaping: True
  camera_names: "custom"
  custom_camera_name: "custom" 
  camera_depths: True
  custom_camera_trans_matrix: [ [ 0.011358,  0.433358, -0.901150,  1220.739746], 
                                [ 0.961834,  0.241668,  0.128340, -129.767868], 
                                [ 0.273397, -0.868215, -0.414073,  503.424103], 
                                [ 0.000000,  0.000000,  0.000000,  1.000000] ]
  custom_camera_conversion: False
  custom_camera_attrib:  {"fovy": 36}
  controller_configs: 
    type: "OSC_POSE"
    input_max: 1
    input_min: -1
    output_max: [0.05, 0.05, 0.05, 0.5, 0.5, 0.5]
    output_min: [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5]
    kp: 150
    damping_ratio: 1
    impedance_mode: "fixed"
    kp_limits: [0, 300]
    damping_ratio_limits: [0, 10]
    position_limits: [[-.inf,-.inf, 0.819],[.inf, .inf, .inf]]
    orientation_limits: null
    uncouple_pos_ori: true
    control_delta: true
    interpolation: null
    ramp_ratio: 0.2
  
wandb_callback:
  gradient_save_freq: 10000
  verbose: 2

eval_callback:
  callback_on_new_best: null
  n_eval_episodes: 20
  eval_freq: 6144 
  log_path: './logs_dont_crash_in_table/' 
  best_model_save_path: './logs_dont_crash_in_table/'
  deterministic: False
  render: False 
  verbose: 1 
  warn: True

gymwrapper:
  observations: ["custom_image_rgbd",'robot0_eef_pos', 'gripper_status']
  smaller_action_space: True
  xyz_action_space: False
  rgbd: False

wandb:
  project: "sb3_lift_real"
  sync_tensorboard: True 
  save_code: True

# Settings used for file handling and logging (save/load destination etc)
file_handling:
  # Logging with Tensorboard and saving trained models
  save_model_folder: "trained_models"
  save_model_filename: "ppo_dont_crash_in_table"
  # Loading of trained models
  load_model_folder: "trained_models"
  load_model_filename: null



